version: "3"

volumes:
  nocobase_storage:
  nocobase_postgres_storage:

networks:
  nocobase:
    driver: bridge

services:
  app:
    image: nocobase/nocobase:latest-full
    restart: always
    init: true
    networks:
      - nocobase
    depends_on:
      - postgres
    env_file: .env
    environment:
      - APP_KEY=${APP_KEY}
      - ENCRYPTION_FIELD_KEY=${ENCRYPTION_FIELD_KEY}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ} 
    volumes:
      - nocobase_storage:/app/nocobase/storage
    ports:
      - "13000:80"

  postgres:
    image: postgres:16
    restart: always
    command: postgres -c wal_level=logical
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - nocobase_postgres_storage:/var/lib/postgresql/data
    networks:
      - nocobase

  cloudflared: # Tunnel kết nối subdomain
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - nocobase
